name: Build Documentation
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: docs/source
